config/routes.rb
Rails.application.routes.draw do
    resources :users
    root 'movies#search'

    get 'movies/search' => 'movies#search'
    get 'movies/search_result' => 'movies#search_result'

    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  
  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: {case_sensitive: false}

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def search
    @genres = TheMovieDbService.genres
    # @movie = TheMovieDbService.new(params).search.sample
    # Movie.create(title: @movie['title'])
    # @movies = HTTParty.get("https://api.themoviedb.org/3/discover/movie?with_genres=28&include_video=false&include_adult=false&sort_by=popularity.desc&language=en-US&api_key=4722ab521bc96d24058c095db629b2cd")
  end

  def search_result
    @movie = TheMovieDbService.new(params).search.sample
    @search_link = request.url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render 'new'
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            log_in user
            redirect_to user
        else
            flash.now[:danger] = 'Invalid email/password combination'
            render 'new'
        end
    end

    def destroy
        log_out
        redirect_to root_url
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @users = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'Welcome to JustPickIt' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 50)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/about.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" charset="utf-8"/>
        <title>About</title>
    </head>
    <body>
      <h1>About</h1>
      <p>
        JustPickIt is an application that will generate a random
        movie for you when you are not sure on what to movie to
        watch. You can pick your own genre and when you click search
        it will find you a movie in that genre you chose. It is as
        simple as that. JustPickIt.
      </p>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>JustPickIt</title>
        <link
            href="https://fonts.googleapis.com/css?family=Allura|Amatic+SC|Calligraffitti|Cinzel|Dancing+Script|Euphoria+Script|Handlee|Homemade+Apple|Josefin+Sans|Josefin+Slab|Julius+Sans+One|Mr+De+Haviland|News+Cycle|Nixie+One|Open+Sans+Condensed:300|Parisienne|Poiret+One|Quattrocento|Questrial|Quicksand|Qwigley|Raleway|Ruthie|Yellowtail"
            rel="stylesheet">

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>
        <body>

            <div class="dropdown">
      <button class="dropbtn">About</button>
      <div class="dropdown-content">
         <a>JustPickIt is an application that will generate a random
            movie for you when you are not sure on what movie to
            watch. You can pick your own genre and when you click search
            it will find you a movie in that genre you chose. It is as
            simple as that. JustPickIt.</a>
  </div></div>
            <div id="main-title">
                <h1><a href="movies/search_result">Just Pick It</a></h1>
            </div>
            <%= yield %>
        </body>
    </html>

app/views/movies/search.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
    <body>
        <div class="choose">
            <div id="search-options">
                <%=form_tag('/movies/search_result', method: :get) do%>
                <%= select_tag :genre,  options_for_select(@genres.map{ |key, value| [key, value]}), multiple: true %><br>
                <div class="submit">
                    <%= submit_tag 'Go!', id: 'go'%>
                </div>
                <% end %>
            </div>
        </div>
        <div id="footer">
            <div class="container">
                <p>created by: |
                </p>
            </div>
        </div>
    </body>
</html>

app/views/movies/search_result.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <div class="poster">
            <img src="https://image.tmdb.org/t/p/w300_and_h450_bestv2<%= @movie['poster_path']%>">
        </div>
        <div class="text">
            <div id="link">
                <a href="<%= @search_link %>">
                    <p>Don't like it? &nbsp;<i class="fa fa-repeat" aria-hidden="true"></i>&nbsp; try again!</p>
                </a>
            </div>
            <div class="title">
                <p><%= @movie['title'] %> (<%= @movie['release_date'][0,4] %>)
                </p>
            </div>
        </br>

        <div class="overwiew">
            <p>
                <i>Overwiew: &nbsp;
                </i>
                <%= @movie['overview'] %></p>
        </div>
    </br>

</div>
<div id="footers">
    <div class="container">
        <p>created by: |
        </p>
    </div>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 class="sign_up">Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

<!-- <%= link_to 'Back', users_path %> -->

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div id="top-bar"></div>

<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user %>
                Welcome
                <%= @user.name %>!
            </h1>
        </section>
    </aside>
</div>

<p class="email">
    <strong>Email:</strong>
    <%= @user.email %>
</p>

<div>
  <h4 class="seen">Movies Seen:</h4>
</div>

<%= link_to 'Home', root_path %>
<!-- <%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> -->